<?php

namespace dungeonxplorer\hero\class;

use dungeonxplorer\item\Armor;

class Warrior extends \dungeonxplorer\hero\Hero{

    private Armor $armor;     // Armor

    public function hydrate(array $donnees): void
    {
        parent::hydrate($donnees); // TODO: Change the autogenerated stub
        if(isset($donnees['he_armor'])){
            $item = ItemManager::getInstance()->getItem($donnees['he_armor']);
            if($item instanceof Armor)
                $this->armor = $item;
        }

    }


}

?>